---
#tasks install "Docker"
- name: Docker repository
  yum_repository:
    name: DockerCEStable
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    enabled: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present    

# tasks Installing kubelet and kubeadm
- name: Install Kubernetes Repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    enabled: yes
    gpgcakey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
    gpgkey: "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"