# Install Heapster with an InfluxDB backend and a Grafana UI

- name: Verify and remove old version of Git
  yum:
    name: git
    state: absent

- name: Remove old cloned repo
  file:
    state: absent
    path: /home/centos/heapster 
    
- name: install Git version 1.8.3.1 x86_64
  yum:
    name: git-1.8.3.1-6.el7_2.1.x86_64
    state: present

- name: Clone git repo
  git: 
    repo: https://github.com/kubernetes/heapster.git
    dest: /home/centos/heapster
    clone: yes

- name: Delete existing Heapster containers 
  command: /usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf delete deployment --namespace=kube-system heapster
  with_items:
   - deployment
   - svc
   - serviceaccount
  ignore_errors: true

- name: Delete existing Grafana containers 
  command: /usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf delete deployment --namespace=kube-system monitoring-grafana
  with_items:
   - deployment
   - svc
  ignore_errors: true

- name: Delete existing influxdb containers 
  command: /usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf delete deployment --namespace=kube-system monitoring-influxdb
  with_items:
   - deployment
   - svc
  ignore_errors: true

- name: Deploy Heapster containers 
  command: /usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf create -f /home/centos/heapster/deploy/kube-config/influxdb/
  register: heapster
  ignore_errors: true

- debug:
    var: heapster.stdout_lines
