# Install Heapster with an InfluxDB backend and a Grafana UI

# Install git (version 1.8.3) and clone Heapster repo
- name: Verify and remove old version of Git
  yum:
    name: git
    state: absent

- name: install Git version 1.8.3.1 x86_64
  yum:
    name: git-1.8.3.1-6.el7_2.1.x86_64
    state: present

- git: 
    repo: https://github.com/kubernetes/heapster.git
    dest: /home/centos/heapster
    clone: yes

#- name: Deploy Heapster containers 
#      command: /usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf create -f deploy/kube-config/influxdb/
#      register: heapster
#      ignore_errors: true

#    - debug:
#        var: heapster.stdout_lines

#- name: Wait for Heapster to be Running
#      shell: "/usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf get pods --all-namespaces | grep heapster"
#      register: task_result
#      until: task_result.stdout.find("Running") != -1
#      retries: 15
#      delay: 10
#      ignore_errors: true    
      
#    - debug:
#        var: task_result.stdout_lines   