# Installing kubelet and kubeadm on edge nodes
- hosts: "{{ clustername }}_edge"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - edge

- hosts: "{{ clustername }}_edgeadd"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - edge