# Create tokek for cluster initialization
#- hosts: localhost
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - role: admission_token

  tasks:
    - debug:
        var: token