# Create tokek for cluster initialization
#- hosts: "{{ clustername }}_master"
- hosts: 127.0.0.1
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - role: create_token