---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://IP_ADDREDD:PORT
  #      https_proxy: http://IP_ADDREDD:PORT
  roles:
    - pre 

- hosts: kubernetes-master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://IP_ADDREDD:PORT
  #      https_proxy: http://IP_ADDREDD:PORT
  roles:
    - master 
    
- hosts: kubernetes-edge
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://IP_ADDREDD:PORT
  #      https_proxy: http://IP_ADDREDD:PORT
  roles:
    - edge

- hosts: kubernetes-master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://IP_ADDREDD:PORT
  #      https_proxy: http://IP_ADDREDD:PORT
  roles:
    - clustermaster 

- hosts: kubernetes-edge
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://IP_ADDREDD:PORT
  #      https_proxy: http://IP_ADDREDD:PORT
  roles:
    - clusteredge
