# http://kubernetes.io/docs/getting-started-guides/kubeadm/
#
# Example to start playbook:
#    ansible-playbook install-cluster.yml -e "cluster_name=kubernetes"
#

# Basic task requirement
---
- hosts: "{{ cluster_name }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - pre 
    
# Installing kubelet and kubeadm on master node
- hosts: "{{ cluster_name }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - master 

# Installing kubelet and kubeadm on edge nodes
- hosts: "{{ cluster_name }}_edge"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - edge

# Initializing master
- hosts: "{{ cluster_name }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confmaster 

# Installing a pod network
- hosts: "{{ cluster_name }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - podnet 

# Joining edge nodes to cluster
- hosts: "{{ cluster_name }}_edge"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confedge
