#
# Example launch playbook:
#    ansible-playbook install-cluster.yml -e "cluster_name=kubernetes"
#
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - pre 

- hosts: kubernetes-master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - master 
    
- hosts: kubernetes-edge
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - edge

- hosts: kubernetes-master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confmaster 

- hosts: kubernetes-edge
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confedge
