# Initializing master
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confmaster 


# Installing a pod network on master
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - podnet 