---
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - dashboard
    - status
    - heapster
# TO DO    - nexus
# TO DO    - containers
