# RUN PLAYBOOK
#
# Read README.md for detail
#
# ansible-playbook -i kubernetes/inventories/production/hosts site.yml -e clustername=kubernetes -u centos

---
# Main file: site.yml
- include: /includejob/all-node.yml
- include: /includejob/master-node.yml
- include: /includejob/edge-nodes.yml
- include: /includejob/gentoken.yml
- include: /includejob/k-master.yml
- include: /includejob/k-edge.yml
- include: /includejob/k-plugin.yml
# TO DO - include: /includejob/glusterFS.yml
# TO DO - include: /includejob/nexus.yml