# RUN PLAYBOOK
#
# Read README.md for detail
#
# ansible-playbook -i kubernetes/inventories/production/hosts site.yml -e clustername=kubernetes -u centos

---
# Main file: site.yml
- include: all-node.yml
- include: master-node.yml
- include: edge-nodes.yml
- include: gentoken.yml
- include: k-master.yml
- include: k-edge.yml
- include: k-plugin.yml
# TO DO - include: glusterFS.yml
# TO DO - include: nexus.yml