# Cluster inizialization on Master Node with kubeadm
---
    - name: Delete old kubernetes conf file
      command: rm -f $HOME/admin.conf
    
    - name: Reset old kubernetes installation
      command: kubeadm reset
        
    - name: Read token from file
      include_vars: cfg/{{ clustername }}/token.yml

    # TO DO kubeadm token generate
    - name: Save master_ip_address
      shell: echo "master_ip_address{{ ':' }} {{ master_ip_address }}" > cfg/{{ clustername }}/master_ip_address.yml

    - name: Initialize master
      command: kubeadm init --token {{ admission_token }}
      args:
      register: master_init
      ignore_errors: true
      
    - name: Copy admin file on user $HOME
      command: cp /etc/kubernetes/admin.conf $HOME/
            
    - name: Export env var for Kubernetes
      lineinfile:
        dest=/root/.bashrc 
        line="export KUBECONFIG=/root/admin.conf"
        state=present
        insertafter=EOF
        create=True
    
    # Wait for Kube-DNS running
#    - name: Wait for Kube-DNS pod running
#      shell: "kubectl --kubeconfig /etc/kubernetes/admin.conf get pods --all-namespaces | grep kube-dns"
#      register: result
#      until: result.stdout.find("Running") != -1
#      retries: 30
#      delay: 10          

    - name: Get dns service address
      shell: kubectl get services --all-namespaces | grep kube-dns | awk "{print \$3}"
      register: kubednsaddress

    - name: Wait for dns to be ready
      wait_for: host={{ kubednsaddress.stdout }} port=53 state=started timeout=1800
    
    # Cluster add CNI network weave-kube
    - name: Install pod network "weave-kube 1.6"
      command: /usr/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://git.io/weave-kube-1.6
      register: pod_network
      ignore_errors: true

    - debug:
        var: pod_network.stdout_lines        