---
#Tasks mount "GlusterFS" replicated FS

#Create a directory if it doesn't exist
#- file:
#    path: /glusterfs/volume1
#    state: directory
#    mode: 0755

- name: Ensure Gluster mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_mount_dir }}"

# Edit fstab

#- mount: name=/glusterfs/volume1 src="{{inventory_hostname}}:/glustervol1" fstype=glusterfs state=mounted

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted