---
#Tasks mount "GlusterFS" replicated FS

#Create a directory if it doesn't exist
- file:
    path: /glusterfs/volume1
    state: directory
    mode: 0755

- name: Ensure Gluster brick and mount directories exist.
      file: "path={{ item }} state=directory mode=0775"
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

# Edit fstab

#- mount: name=/glusterfs/volume1 src="{{inventory_hostname}}:/glustervol1" fstype=glusterfs state=mounted

- name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted


- name: Edit fstab and mount the XFS volume permanently
  action: name=/bricks/brick1 src=/dev/vg_brick1/lv_brick1 fstype=xfs opts=noatime state=mounted
