---
#Tasks mount "GlusterFS" replicated file system

- name: Ensure Gluster mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_mount_dir }}"

- name: Ensure old Gluster volume is unmounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: unmounted

- pause:
    seconds: 15

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted

- name: Check gluster volume info
  shell: /usr/sbin/gluster volume info
  register: gluster_volume_info
  ignore_errors: true  

- debug:
        var: gluster_volume_info.stdout_lines