# Cluster inizialization on Master Node with kubeadm
---
    - name: Read token from file
      include_vars: cfg/{{ clustername }}/token.yml

    - name: Save master_ip_address
      shell: echo "{{ master_ip_address }}" > cfg/{{ clustername }}/master_ip_address.yml
      delegate_to: 127.0.0.1
      become: false

    - name: Initialize master
      command: kubeadm init --token {{ admission_token }}
      args:
      register: master_init
      ignore_errors: true
    
    - name: cccc
      command: cp /etc/kubernetes/admin.conf $HOME/
    
    - name: bbbb
      command: chown $(id -u):$(id -g) $HOME/admin.conf
      
    - name: ffff
      command: export KUBECONFIG=$HOME/admin.conf
    
    - name: gggg
      command: echo "source KUBECONFIG=$HOME/admin.conf" >> ~/.bashrc
