#tasks install "Kubectl"
#- name: view last "kubctl" stable version
#  get_url: 
#    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
#    dest: /tmp/stable.txt

    
- name: download kubctl and make executable in folder  /usr/local/bin/
  tasks:

      - shell: cat /tmp/stable.txt
        register: stable_contents

#  vars:
#     contents: "{{ lookup('file', '/tmp/stable.txt') }}"
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ register }}/bin/linux/amd64/kubectl
#    url: https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    force_basic_auth: yes
    mode: 0750
