# Cluster inizialization on Master Node with kubeadm
---
    - name: delete old kubernetes conf file
      command: rm -f $HOME/admin.conf
    
    - name: reset old kubernetes installation
      command: kubeadm reset
        
    - name: Read token from file
      include_vars: cfg/{{ clustername }}/token.yml

    - name: Save master_ip_address
      shell: echo "{{ master_ip_address }}" > cfg/{{ clustername }}/master_ip_address.yml
      delegate_to: 127.0.0.1
      become: false

    - name: Initialize master
      command: kubeadm init --token {{ admission_token }}
      args:
      register: master_init
      ignore_errors: true
      
    - name: Copy admin file on user $HOME
      command: cp /etc/kubernetes/admin.conf $HOME/
      environment:
        KUBECONFIG: $HOME/admin.conf
            
    - name: Update bashrc
      lineinfile:
        path=~/.bashrc 
        line="KUBECONFIG= $HOME/admin.conf"
        state=present
        insertafter=EOF
        create=True
    
#    - name: source bashrc
#      shell: source $HOME/.bashrc
#      args:
#      executable: /bin/bash