# Cluster inizialization on Master Node with kubeadm
---
    - name: delete old kubernetes conf file
      command: rm -f $HOME/admin.conf
    
    - name: reset old kubernetes installation
      command: kubeadm reset
        
    - name: Read token from file
      include_vars: cfg/{{ clustername }}/token.yml

    - name: Save master_ip_address
      shell: echo "{{ master_ip_address }}" > cfg/{{ clustername }}/master_ip_address.yml
      delegate_to: 127.0.0.1
      become: false

    - name: Initialize master
      command: kubeadm init --token {{ admission_token }}
      args:
      register: master_init
      ignore_errors: true
    
    - name: Copy admin file on user $HOME
      vars:
         local_home: "{{ lookup('env','HOME') }}" 
      command: cp /etc/kubernetes/admin.conf $HOME/
      environment:
        KUBECONFIG: $HOME/admin.conf
            
#    - name: Insert permanent env var
#      command: echo "source KUBECONFIG=$HOME/admin.conf" >> ~/.bashrc

    - name: Update bashrc for PythonBrew for foo user
      vars:
         local_home: "{{ lookup('env','HOME') }}" 
      lineinfile:
      dest=~/.bashrc
        line="KUBECONFIG= {{ local_home }} /admin.conf"
        state=present
        insertafter=EOF
        create=True
    
    - name: source bashrc
      action: shell source ~/.bashrc