# Join Edge Nodes to cluster with kubeadm
---  
  pre_tasks:

    - name: Read token
      include_vars: cfg/{{ clustername }}/token.yml
      
    - name: Read master_ip_address
      include_vars: cfg/{{ clustername }}/master_ip_address.yml

  tasks:

    - debug:
        var: admission_token
      run_once: true

    - debug:
        var: master_ip_address
      run_once: true

    - name: Join nodes to cluster
      command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443
      args:
      register: node_join
      ignore_errors: true