#tasks Add "Kubectl" bash comletion environment
- lineinfile:
    path: ~/.bashrc
    line: 'source <(kubectl completion bash)'

#- name: Add Kubectl bash comletion environment
#  command: echo "source <(kubectl completion bash)" >> ~/.bashrc
