#tasks install "Kubectl"

- name: Clean old kubectl file
  file:
    state: absent
    path: /usr/local/bin/kubectl
    
- name: check "kubctl" stable version
  get_url: 
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    dest: /tmp/stable.txt
  when: kubectl_version is undefined
  
- name: return stable.txt to registered var
  command: cat /tmp/stable.txt
  register: version_stdout
  when: kubectl_version is undefined
  
- name: Set Kubernetes Version 
  set_fact:
    version: "{{ kubectl_version }}"
  when: kubectl_version is defined

- name: Set Kubernetes Version 
  set_fact:
    version: "{{ version_stdout.stdout }}"
  when: kubectl_version is undefined

- name: download kubctl and make executable in folder  /usr/local/bin/
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    force_basic_auth: yes
    mode: 0750
