# Join Edge Nodes to cluster with kubeadm
---

- name: Reset existing kubernetes installation
  command: kubeadm reset
  ignore_errors: true

- name: Read token
  include_vars: /cfg/{{ clustername }}/token.yml
      
- name: Read master_ip_address
  include_vars: /cfg/{{ clustername }}/master_ip_address.yml

- debug:
    var: admission_token
  run_once: true

- debug:
    var: master_ip_address
  run_once: true
    
- name: Debug admission token
  debug:
    msg: "Admission token: {{ admission_token }}"

- name: Join edge nodes to cluster
  command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443
  register: node_join

- debug:
    var: node_join.stdout_lines     