# Join Edge Nodes to cluster with kubeadm
---  
    
    - name: Read token
      include_vars: /cfg/{{ clustername }}/token.yml
      
    - name: Read master_ip_address
      include_vars: /cfg/{{ clustername }}/master_ip_address.yml

    - name: Reset old kubernetes installation
      command: kubeadm reset

    - debug:
        var: admission_token
      run_once: true

    - debug:
        var: master_ip_address
      run_once: true

    - name: Join nodes to cluster
      command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443
      args:
      register: node_join
      ignore_errors: true
    
    - debug:
        var: node_join.stdout_lines
      ignore_errors: true
    
    - pause:
        minutes: 1