# Join Edge Nodes to cluster with kubeadm
---  
    - name: Reset old kubernetes installation
      command: kubeadm reset

    - name: Read token
      include_vars: cfg/{{ clustername }}/token.yml
      
    - name: Read master_ip_address
      include_vars: cfg/{{ clustername }}/master_ip_address.yml

    - debug:
        var: admission_token
      run_once: true

    - debug:
        var: master_ip_address
      run_once: true

    - name: Join nodes to cluster
      command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443
      args:
      register: node_join
      ignore_errors: true
    
    - debug:
        var: node_join.stdout_lines
      ignore_errors: true
    
    - name: Wait for Nodes to be ready
      shell: "kubectl get nodes"
      register: task_result
      until: task_result.stdout.find("Running") != -1
      retries: 30
      delay: 10    