---
#Tasks install and start "glusterd" service

- name: == YUM == Uninstall GlusterFS old repository
  yum: name={{ item }} state=absent
  with_items:
   - centos-release-gluster
  ignore_errors: True

- name: == YUM == Install GlusterFS repository
  yum: name={{ item }} state=latest
  with_items:
   - centos-release-gluster

- name: == YUM == Uninstall GlusterFS old packages
  yum: name={{ item }} state=absent
  with_items:
   - glusterfs-server
  ignore_errors: True

- name: == YUM == Install GlusterFS packages
  yum: name={{ item }} state=latest
  with_items:
   - glusterfs-server

- name: == Service Start - Enable & Start GlusterFS
  service:
    name: glusterd
    state: started
    enabled: yes

#Tasks inizialize disk with lvm
- name: Set name and format gluster disk
  set_fact:
    version: "{{ glusterdev_name }}"
  
- name: Volume partitioning
  parted:
    device: /dev/{{ glusterdev_name }}
    number: 1
    flags: [ lvm ]
    state: present
    part_start: 0%
    part_end: 100%

- name: Create Volume Group
  lvg:
    vg: vg_brick1
    pvs: /dev/{{ glusterdev_name }}

#Configure Volume format xfs and mount volume
- name: Create Logical Volume
  lvol:
    vg: vg_brick1
    lv: lv_brick1
    size: 100%FREE    
  ignore_errors: True

- name: Format volume with XFS
  filesystem: 
    fstype: xfs 
    dev: /dev/vg_brick1/lv_brick1
    force: yes
  ignore_errors: True

- name: Verify Gluster brick directory.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "{{ gluster_brick_dir }}"

- name: Edit fstab and mount the XFS volume
  mount:
    name: /bricks/brick1
    src: /dev/vg_brick1/lv_brick1
    fstype: xfs
    opts: "noatime"
    state: mounted
