---

#Tasks install "Docker"
- name: Uninstall Docker & Utility existing versions
  yum: name={{ item }} state=absent
  with_items:
   - docker
   - docker-common
   - container-selinux
   - docker-selinux
   - docker-engine
   - yum-utils
   - device-mapper-persistent-data
   - lvm2
  ignore_errors: True

- name: Install Docker utility
  yum: name={{ item }} state=latest
  with_items:
   - yum-utils
   - device-mapper-persistent-data
   - lvm2

- name: Check if Docker repo is already configured
  stat: path={{ docker_repofile_path }}  
  register: docker_repofile_result
    
- name: Add Docker repository
  command: yum-config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo
  when: not docker_repofile_result.stat.exists
  
- name: Install Docker service
  yum: name={{ item }} state=latest
  with_items:
   - docker

- name: Docker service Enable & Start 
  service:
    name: docker
    state: started
    enabled: yes
        
- name: Clean existing repo and install kubernetes repo
  file:
    state: absent
    path: /etc/yum.repos.d/kubernetes.repo

- name: Install kubernetes repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

# Tasks Installing kubelet and kubeadm    
- name: Uninstall old versions kubelet kubeadm kubernetes-cni
  yum: name={{ item }} state=absent
  with_items:
   - kubelet
   - kubeadm
   - kubernetes-cni
  ignore_errors: True

- name: Install kubelet kubeadm kubernetes-cni
  yum: name={{ item }} state=latest
  with_items:
   - kubelet
   - kubeadm
   - kubernetes-cni

- name: Kubelet Enable & Start
  service:
    name: kubelet
    state: started
    enabled: yes
