---
# Check kubernetes pods status Running

- name: Wait for all pods to be Running
  shell: "/usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf get pods --all-namespaces"
  register: task_result
  until: 
    - '"NotReady" not in task_result.stdout'
    - '"Pending" not in task_result.stdout'
  retries: 20
  delay: 10
  ignore_errors: true    
      
- debug:
    var: task_result.stdout_lines   