---

- name: Generate token
#  shell: python -c 'import random; print "%0x.%0x" % (random.SystemRandom().getrandbits(3*8), random.SystemRandom().getrandbits(8*8))'
  shell: kubeadm token generate
  register: token_raw

- set_fact:
    admission_token: '{{ token_raw.stdout }}'

- file:
    path: /cfg/{{ clustername }}
    state: directory

- name: Save token.yml file
  copy:
    dest: /cfg/{{ clustername }}/token.yml
    content: "admission_token: {{ admission_token }}"
