---
#Tasks configure "GlusterFS" replica
  
# Gluster volume configuration.
- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- debug:
        var: gluster_volume_info.stdout_lines

#- name: Create a replicated Glusterfs volume
#  shell: gluster volume create glustervol1 replica 3 transport tcp {{ edge1gfs }}:/bricks/brick1/brick {{ edge2gfs }}:/bricks/brick1/brick {{ edge3gfs }}:/bricks/brick1/brick
#  register: task_result

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    transport: tcp
    replicas: "{{ numedges }}"
    cluster: "{{ groups.{{ clustername }}_gfedge | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name:
  shell: gluster volume start glustervol1
  register: gluster_start_info

- debug:
        var: gluster_start_info.stdout_lines


- name:
  shell: gluster volume info
  register: gluster_volume_info

- debug:
        var: gluster_volume_info.stdout_lines



