# Kubernetes guide kubeadm cluster
#
# Example to start playbook:
# ansible-playbook install-cluster.yml -e clustername=kubernetes -u centos
# 
# Vars to change "value":
# clustername="value"
# Username    -u "value"


# Basic task requirement
---
- hosts: "{{ clustername }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - pre 
    
    
# Installing kubelet and kubeadm on master node
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - master 


# Installing kubelet and kubeadm on edge nodes
- hosts: "{{ clustername }}_edge"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - edge


# Create tokek for cluster initialization
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - role: admission_token

  tasks:
    - debug:
        var: token
        
        
# Initializing master
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confmaster 


# Installing a pod network on master
- hosts: "{{ clustername }}_master"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - podnet 


# Joining edge nodes to cluster
- hosts: "{{ clustername }}_edge"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
    - confedge
