---
# Create etc/hosts file on Kubernetes Servers with all Cluster entry
- name: change file etc/hosts
  template: src=hosts.j2 dest=/etc/hosts

# Disable Firewalld on all Kubernetes Server
- name: == Service Stop - Disable autostart == Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

# Disable "SELinux"
- name: == SYSTEM == Turn Off SELinux
  selinux:
    state: disabled

# Install and enable "chronyd" for ntp synchronization
- name: Install chrony
  yum: name=chrony
- name: Start the chronyd service
  action: service name=chronyd state=started
  
# Install utility "wget"
- name: Install wget
  yum: name=wget
  
# Install utility "bash-completion"
- name: Install bash-completion
  yum: name=bash-completion
