#Base tasks on all Kubernetes Servers
---

- name: Create node entry in etc/hosts file
  template: src=hosts.j2 dest=/etc/hosts
  
- name: Firewalld service Stop & Disable autostart 
  service:
    name: firewalld
    state: stopped
    enabled: no
  
- name: Turn Off SELinux
  selinux:
    state: disabled
  ignore_errors: yes

- name: Install chrony
  yum: name=chrony

- name: Start the chronyd service
  action: service name=chronyd state=started
  
- name: Install wget utility
  yum: name=wget
  
- name: Install bash-completion utility
  yum: name=bash-completion
