---
# Create etc/hosts file on Kubernetes Servers with all Cluster entry
- name: change file etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
  tags:
    - file_hosts
  
# Disable Firewalld on all Kubernetes Server
- name: == Service Stop - Disable autostart == Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  tags:
    - firewalld_dis  
  
# Disable "SELinux"
- name: == SYSTEM == Turn Off SELinux
  selinux:
    state: disabled
  tags:
    - selinux_dis

- name: Disable SELinux now
  command: setenforce 0
  ignore_errors: yes

# Install and enable "chronyd" for ntp synchronization
- name: Install chrony
  yum: name=chrony
- name: Start the chronyd service
  action: service name=chronyd state=started
  tags:
    - chrony_ntp
  
# Install utility "wget"
- name: Install wget
  yum: name=wget
  tags:
    - wget_add
  
# Install utility "bash-completion"
- name: Install bash-completion
  yum: name=bash-completion
  tags:
    - bash_add 