#Base tasks on all Kubernetes Servers
---

# Create etc/hosts file on Kubernetes Servers
- name: change file etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
  
# Disable Firewalld
- name: == Service Stop - Disable autostart == Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  
# Disable "SELinux"
- name: == SYSTEM == Turn Off SELinux
  selinux:
    state: disabled
  ignore_errors: yes

# Install and enable "chronyd" for time synchronization
- name: Install chrony
  yum: name=chrony

- name: Start the chronyd service
  action: service name=chronyd state=started
  
# Install "wget" utility
- name: Install wget
  yum: name=wget
  
# Install "bash-completion" utility 
- name: Install bash-completion
  yum: name=bash-completion