---  
# Check kubernetes nodes status Ready

- pause:
    seconds: 10
    
- name: Wait for Nodes to be ready 1
  shell: "/usr/bin/kubectl --kubeconfig /etc/{{ clustername }}/admin.conf get nodes"
  register: task_result
  until: 
    - '"NotReady" not in task_result.stdout'
    - '"ContainerCreating" not in task_result.stdout'
  retries: 30
  delay: 15
  ignore_errors: true    

- debug:
    var: task_result.stdout_lines   